### ISSUE TITLE
slow download for long-term daily data requests

### ISSUE THREAD

**Issue by JJguri** [cheginit/pydaymet#13] opened 2021-05-18 04:22 UTC
**Is your feature request related to a problem? Please describe.** 
I am trying to download **daily** data (four variables) for a 40 km * 40 km spatial resolution (approx) across 31 years but the download is taking a lot of time. The code I am using is described below:

```
from pynhd import NLDI
import pydaymet as daymet
var = ["srad","tmin","tmax","prcp"]
dates = ("1989-01-01", "2019-12-31")
ext = (-95.75, 46.25, -94.25, 47.75)
data = daymet.get_bygeom(ext, dates, variables=var, region="na")
```

I need to download these variables and time period for the entire USA, so I would like to know which is the limiting factor to improve the speed of the data download from the API.

**Describe the solution you'd like**
Improve the speed of the data download from the API.

**Describe alternatives you've considered**
any at the moment.

**Additional context**
I am running the code through Jupyter Notebook on a 6 core laptop computer with 32 GB RAM.

**Comment by cheginit** [comment] 2021-05-18 06:00
You're trying the download the entire Daymet dataset. It's supposed to take long. PyDaymet already provides the fastest possible way of getting the data through asynchronous send/requests and persistent caching that I recently added (still haven't released it officially).

I am planning to release the new version this week that additionally provides a command-line interface to PyDaymet.

In any case, I don't think getting the entire database in one go is going to work since it will not fit into your system's memory. You must consider breaking down you requests and save them to your disk intermittently. For example, you can write a for-loop to get the data for a year and save it to disk in each iteration:

```python
for yr in range(1989, 2020):
	daymet.get_bygeom(ext, yr, variables=var).to_netcdf(f"{yr}.nc")
```

This is a more robust way of handling your request. You can play around with the years based on your system's memory:

```python
for yr in range(1989, 2020 - 5, 5):
	daymet.get_bygeom(ext, list(range(yr, yr + 6)), variables=var).to_netcdf(f"{yr}-{yr+5}.nc")
```

**Comment by cheginit** [comment] 2021-05-18 06:25
Having said that, I think downloading the entire dataset should be dealt with using another approach than the netcdf subsetter service that PyDaymet uses. Since, as the name suggests, it's for subetting the database not getting it in its entirety. I think using their http server will be much faster. I will into it.

**Comment by JJguri** [comment] 2021-05-18 12:58
thanks @cheginit! your answer was really useful.

Can I select avoid the download of the `lat` and `lon` variables using pydaymet?

The issue is that now I have several .nc files in a folder and I trying to read the files using the following xarray function:

```
data = xr.open_mfdataset(r'...\*.nc')
```
and I am getting an issue related to ambiguous variables. Please see the xarray error below:

```
MergeError: unable to determine if these variables should be coordinates or not in the merged result: {'lon', 'lat'}
```

**Comment by cheginit** [comment] 2021-05-18 14:30
I am unable to reproduce this issue. Here's a MWE that works without this issue:
```python
import pydaymet as daymet
from shapely.geometry import Polygon
import xarray as xr

geometry = Polygon(
    [
        [-69.77, 45.07],
        [-69.31, 45.07],
        [-69.31, 45.45],
        [-69.77, 45.45],
        [-69.77, 45.07],
    ]
)
for yr in range(1989, 1991):
    daymet.get_bygeom(geometry, yr, variables=["prcp", "tmin"]).to_netcdf(
        f"all_{yr}.nc"
    )

ds = xr.open_mfdataset("all*.nc")
```
![image](https://user-images.githubusercontent.com/13016644/118669087-12604b00-b7bb-11eb-87fe-c595c5874240.png)



You might want to try setting coords argument to "minimal":

```python
ds = xr.open_mfdataset("*.nc", coords="minimal")
```

**Comment by JJguri** [comment] 2021-05-19 05:02
I solved the issue by applying the code you provided thanks

**Comment by cheginit** [comment] 2021-05-20 22:03
Since the issue is resolved, I am going to close this. Please feel free to re-open if needed!

**Closed by cheginit** 2021-05-20 22:03 UTC

**Comment by Flash-Of-Thunder** [comment] 2022-01-06 07:59
Hey again @cheginit and fellow climate fanatics, coming back to dive into this topic some more. So I'm implementing this strategy and it seems to be working well except I still hit a wall and I'm wondering if there is some memory leak happening with my code, I tried to use `.close()` but doesn't seem to be doing the trick.

I'm looping over multiple basins for 1980-2020. I noticed that it goes very fast except it suddenly slows to a crawl again. I was digging deeper and watching the timing of my yearly output files from this line `raw_daymet.to_netcdf(f"{output_folder_temp}/{yr}.nc",mode = "w")` I was getting stuck on a particular basin (10258000), the first few years are done in seconds and then it slows down drastically. I increased the RAM on my cluster from 16 GB to 44 GB and it flew through the first 15 years before again slowing down. 

```
for basin in basins:
    # Collect gauge/basin geometry
    geometry = NLDI().get_basins(basin).geometry[0]
    # Collect raw daymet
    for yr in range(start_year, end_year+1):
        raw_daymet = daymet.get_bygeom(geometry, yr, pet="hargreaves_samani")
        raw_daymet.to_netcdf(f"{output_folder_temp}/{yr}.nc",mode = "w")
        raw_daymet.close

    raw_daymet_all_years = xr.open_mfdataset(f"{output_folder_temp}/*.nc", coords="minimal")

```

I'll ask some others and post here if I figure out what's going on. 

Cheers!

**Comment by cheginit** [comment] 2022-01-06 16:32
@Flash-Of-Thunder PyDaymet uses response caching, i.e., it doesn't download data twice (unless the data on the server is changed) instead it reads repeated requests from the cache file. That's why on your second attempt it went fast!

Once, I downloaded 15 years of climate data for over 300 watersheds across US using one node of a cluster with 64 GB RAM. I didn't check its performance though and just got the results the next day. So, it should technically work.

My recommendations:

- You don't need a loop for getting basins. You can easily pass all the station IDs as a list to `get_basins` and get a `GeoDataFrame` back. It's even efficient! Then do `for g, yr in itertools.product(basins.geometry, range(start_year, end_year+1)):`
- Bring `xr.open_mfdataset` out of that loop. It will be better (from both programming and performance aspects) to have a function (or block of code) for getting raw data and another for processing them.
- If you're planning to run it on a cluster, alternatively, you can use PyDaymet's CLI to get the data with the same year-by-year approach and do the post-processing later:
```bash
$ pydaymet geometry -h
Usage: pydaymet geometry [OPTIONS] FPATH

Retrieve climate data for a dataframe of geometries.

FPATH: Path to a shapefile (.shp) or geopackage (.gpkg) file.
This file must have four columns and contain a ``crs`` attribute:
    - ``id``: Feature identifiers that daymet uses as the output netcdf filenames.
    - ``start``: Start time.
    - ``end``: End time.
    - ``geometry``: Target geometries.
    - ``time_scale``: (optional) Time scale, either ``daily`` (default), ``monthly`` or ``annual``.
    - ``pet``: (optional) Method to compute PET. Supported methods are:
               ``penman_monteith``, ``hargreaves_samani``, ``priestley_taylor``, and ``none`` (default).
    - ``alpha``: (optional) Alpha parameter for Priestley-Taylor method for computing PET. Defaults to 1.26.

Examples:
    $ pydaymet geometry geo.gpkg -v prcp -v tmin

Options:
-v, --variables TEXT  Target variables. You can pass this flag multiple
                        times for multiple variables.

-s, --save_dir PATH   Path to a directory to save the requested files.
                        Extension for the outputs is .nc for geometry and .csv
                        for coords.

-h, --help            Show this message and exit.
```

**Comment by Flash-Of-Thunder** [comment] 2022-01-09 04:31
Thanks for this, very clarifying about the response caching. 

I also appreciate the tip about bringing the processing out of the loop, it did make it more straightforward and easier to catch errors. I'll use this approach going forward.
